### ISSUE TITLE
Clients Lab

### ISSUE THREAD

**Issue by kiriti811** [kiriti811/SBEC#10]
set the following before you run the scripts 

ls -ltr /var/run/cloudera-scm-agent/process/ | grep 'HUE'

export HUE_CONF_DIR=/var/run/cloudera-scm-agent/process/680-hue-HUE_SERVER

export HUE_DATABASE_PASSWORD=scm

echo  ${JAVA_HOME}/bin/java

export HUE_IGNORE_PASSWORD_SCRIPT_ERROR=1

export HUE_SECRET_KEY=admin

 ./hue useradmin_sync_with_unix

**Comment by kiriti811** [comment]
enable sentry

go to sentry and check for following configurations

1
2
3
4
<property>
    <name>sentry.service.allow.connect</name>
    <value>impala,hive,solr,hue</value>
</property>


<property>
  <name>sentry.service.admin.group</name>
  <value>hive,impala,hue</value>
 </property>


kerbores is set to it or not


go to hue and add sentry service

**Comment by mfernest** [comment]
Your `0_unix_login.png` file doesn't show who is logged in.
`1_hue_lb.png` is ok
No Sentry privileges are apparent in `1_hue_sentry.png`

INC
