### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by kiriti811** [kiriti811/SBEC#11]

**Comment by kiriti811** [comment]
Be very careful while setting up kerberos

if something goes wrong go to 

"/var/kerberos/krb5kdc"

and delete all files except .acl and .conf files 

and re run all the other steps normally

that should work

**Comment by kiriti811** [comment]
!connect jdbc:hive2://localhost:10000/default;principal=hive/hs2.node.com@REALM.COM

hive is hive user and hs2.node.com is the node name of the server in which kerb is installed 

localhost is server in which hive metastore is installed

**Comment by mfernest** [comment]
* Normally you want more encryption types listed for each of your `_enctypes` properties.
* `kdc.conf` is ok
* `kadm5.acl1 is ok
* `kinit.md` is ok
* You probably want a screen shot that shows you the top of the browser window for your own reference

C
