### ISSUE TITLE
Install CM

### ISSUE THREAD

**Issue by kiriti811** [kiriti811/SBEC#15]

**Comment by mikeridley** [comment]
The repo file in your github repo is not going to install the correct version of CM.  Also, I'm not sure if your db.properties is from before you installed CM or after, but it lists the database as being localhost.  Are you using an external host for your database, as per the instrucitons?

**Comment by mfernest** [comment]
I didn't find all the files required for this challenge stage. In addition, as Mike notes, other submissions don't conform to the requirements.

We seem to have had some troubling miscommunication on the requirements, which appears in some of the challenges as well. 

INC-

**Comment by kiriti811** [comment]
There was a misunderstanding from my side. so, installed a different CDH version. I thought of revoking it and install it again but due to time constraints i thought i'll go with the CDH version that i have already installed. 

The db.properties shows "localhost" as i haven't used the correct arguments for the script instead i ran it with localhost. But since i have installed the cloudera in the same node or instance i haven't faced any issue while installing any services.

**Comment by kiriti811** [comment]
The missing file is again my mistake i saved that as 2_cm.md instead of 2_cm.d
