### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by kiriti811** [kiriti811/SBEC#16]

**Comment by kiriti811** [comment]
was struck coz of a wrong sql statement

**Comment by mfernest** [comment]
I couldn't follow the submissions for this stage -- they all seem to be far removed from the instructions. Do you wish to explain what happened to you here?

As Mike commented on the previous stage, setting your `db.properties` file to point to `localhost` does not meet the criteria for the challenge.

**Comment by kiriti811** [comment]
They are not removed but i took some more time then the given prescribed time to complete the task.

The files mentioned are 3_cm.md and 3_hue_installed.png which are still present.

Fore Reference 

![image](https://cloud.githubusercontent.com/assets/18619251/19099012/e1ef1c46-8a77-11e6-9823-5b3d1ba7df8b.png)
