### ISSUE TITLE
Install a MySQL server and replica

### ISSUE THREAD

**Issue by kiriti811** [kiriti811/SBEC#3]
I could install a mysql server but was not able to connect to the master from the slave. After a lot of research found that the one hostname in aws cluster is not able to ping to the other. Ca you please help me find the solution. I have added a security group with all ports open.

**Comment by kiriti811** [comment]
Used **PLAN TWO**

**Comment by kiriti811** [comment]
Had faced issues with pining from one ip to other ip nut could resolve by adding a new rule to the existing security groups

**Comment by mikeridley** [comment]
I was not getting the email alerts on issue comments, so I'm just seeing this now.  Did you get this sorted out?

**Comment by kiriti811** [comment]
yeah i got that sorted out michael. Thank you

**Comment by kiriti811** [comment]
have to update /etc/my.conf file on both master and slave replicas
