### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by kiriti811** [kiriti811/SBEC#7]

**Comment by kiriti811** [comment]
1) done this through cm

has added cluster details in peer 

checked two properties by searching hostname 

and ran a replication

**Comment by kiriti811** [comment]
no major change in the two runs of the terasort just some 30 milliseconds

**Comment by mfernest** [comment]
I see a 17-second difference between your runs, according to the time output. Maybe not an amazing difference, given the total length, but not statistically insignificant either.

As a test of paying attention, I don't ask anyone to gather stats on the cache after the last run. Almost no one ever does but lots of people ask why there is no difference...

**Comment by mfernest** [comment]
NameNode HA enabled, all green.
CM user added, roles changed.
