### ISSUE TITLE
Resources Lab

### ISSUE THREAD

**Issue by kiriti811** [kiriti811/SBEC#9]
In the spread sheet provided i have few doubts. You have specified us to use 20 Vc is that the value we have to provide for CPU's or is it 5 since the number of cpus are multiplied by 5 after the allocation of memory in the bottom if the same sheet.

And thus `maximum.job.maps` depends on the values we give there obviously.

**Comment by mfernest** [comment]
The idea was to go through the calculations on paper the first time, using the specs I gave. This way, you'd could get some interesting numbers. For your lab cluster, the results won't be very interesting because your resource base is so small.

**Comment by mfernest** [comment]
[Here's an example](https://github.com/ag35/SEBC/tree/master/resources/labs) of what I had in mind for lab results.
